[start]
command:/usr/sbin/service cloudflared start
parameters:
type:script
message:Starting cloudflared tunnel

[stop]
command:/usr/sbin/service cloudflared stop
parameters:
type:script
message:Stopping cloudflared tunnel

[restart]
command:/usr/sbin/service cloudflared restart
parameters:
type:script
message:Restarting cloudflared tunnel

[status]
command:/usr/local/bin/cloudflared-configd status; exit 0
parameters:
type:script_output
message:Get cloudflared tunnel status

[version]
command:/usr/local/bin/cloudflared-configd version
parameters:
type:script_output
message:Get cloudflared version

[reconfigure]
command:/usr/local/bin/cloudflared-configd reconfigure
parameters:
type:script
message:Reconfigure cloudflared tunnel
description:Read config.xml, write rc.conf.d, start/stop service
